#!/usr/bin/env bash

install_common() {
  go_install github.com/asdf-vm/asdf/cmd/asdf@v0.16.2
}
setting_common() {
  exe mkdir -p "$HOME/.asdf/completions"
  exe asdf completion zsh | cat_tee "$HOME/.asdf/completions/_asdf"
}
