#!/usr/bin/env bash

install_arch() {
  install_via_os_default
}
install_mac() {
  install_via_os_default
}
setting_common() {
  # state.yml は ~/.local/state 配下なのでディレクトリごとリンクしない
  make_dir_if_needed "$HOME/.config/lazygit"
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/.config/lazygit/config.yml" "$HOME/.config/lazygit/config.yml"
}
