#!/usr/bin/env bash

install_common() { not_supported; }
_install_common() {
  if ! is_dry; then
    export PATH="$HOME/.cargo/bin:$PATH"
  fi

  # exe cargo install cargo-binstall
  local _latest_tag=v1.6.4
  _latest_tag=$(github_latest_release_tag cargo-bins/cargo-binstall)
  exe cargo install cargo-binstall --git https://github.com/cargo-bins/cargo-binstall.git --tag "$_latest_tag"
}
install_wsl() { not_supported; }
install_arch() {
  def_install rustup
  exe rustup default nightly
  # exe rustup default stable
  # exe rustup toolchain install 1.85.0
  # exe rustup default 1.85.0
  _install_common
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  # Configure rust by running rustup-init
  def_install rustup-init
  # Configure rust by running rustup-init
  exe rustup-init
  _install_common
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }

setting_common() {
  # if [[ -e ~/.works.zsh ]]; then
  #   if grep 'CARGO_HOME=' ~/.works.zsh >&/dev/null; then
  #     return
  #   fi
  # fi
  # exe "echo 'export CARGO_HOME=\$HOME/.cargo' >> ~/.works.zsh"
  # exe "echo 'add_path \$CARGO_HOME/bin' >> ~/.works.zsh"
  # rm_dotpath
  _cat_add_settings | cat_you_need_to ~/.works.zsh
}

_cat_add_settings() {
  cat <<'EOF'
export CARGO_HOME=$HOME/.cargo
add_path $CARGO_HOME/bin
EOF
}
