#!/bin/bash

install_common() {
  if ! has pip; then
    log "No pip installed"
    return
  fi
  exe sudo pip install awslogs
}
install_msys()   { not_supported; }
setting_common() {
  :
}
setting_msys()   { no_settings; }

