#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd) && readonly script_dir

main() {
  export PATH=$HOME/win/scoop/apps/vscode/current/bin/:$PATH # for win
  if [[ $# -eq 0 ]]; then
    code --list-extensions >"$script_dir"/extensions
    return
  fi
  cat <"$script_dir"/extensions |
    while read -r line; do
      code --install-extension "$line"
    done
}
main "$@"
