#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  install_via_os_default
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }

cat_neofetch_shell() {
  cat <<'EOF'
#!/usr/bin/env -S bash -e

readonly neofetched_f=/tmp/neofetched

is_tmux_runnning() { [[ -n $TMUX ]]; }
do_neofetch() { neofetch --disable packages; }
already_neofetched() { [[ -e $neofetched_f ]]; }

main() {
  if ! is_tmux_runnning; then
    do_neofetch
    return
  fi
  if already_neofetched; then
    return
  fi
  do_neofetch
  touch $neofetched_f
}
main "$@"
EOF
}
setting_common() { no_settings; }
setting_arch() {
  local dst=/etc/profile.d/neofetch.sh
  [[ -e $dst ]] && return
  log ">>> Generating $dst"
  cat_neofetch_shell |
    if is_dry; then
      cat -
    else
      cat - | sudo tee $dst >/dev/null
    fi
  exe sudo chmod 775 $dst
}
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
