#!/bin/bash

install_common() { not_supported; }
install_arch() {
  cd_work
  if [[ -e yay ]]; then
    exe cd yay
    exe git pull
  else
    exe git clone https://aur.archlinux.org/yay.git
    exe cd yay
  fi
  exe makepkg -si --noconfirm
  exe 'export def_install_cmd="yay -S --noconfirm"'
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
