#!/usr/bin/env bash

is_installed() {
  systemctl is-active --quiet systemd-timesyncd
}

install_common() { not_supported; }
install_arch() {
  exe timedatectl set-ntp true
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { not_supported; }

cat_timesyncd_conf() {
  cat <<'EOF'
NTP=ntp1.jst.mfeed.ad.jp ntp2.jst.mfeed.ad.jp ntp3.jst.mfeed.ad.jp
FallbackNTP=0.arch.pool.ntp.org 1.arch.pool.ntp.org 2.arch.pool.ntp.org 3.arch.pool.ntp.org
EOF
}
setting_arch() {
  local target=/etc/systemd/timesyncd.conf
  if grep -E '^NTP=.*jst.*' $target >&/dev/null; then
    return
  fi
  cat_timesyncd_conf | sudo_tee -a $target
  exe timedatectl status
}

setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
