#!/usr/bin/env bash

install_common() {
  # install_via_os_default
  if ! has asdf; then
    add_dependency_args asdf
    return
  fi
  if ! asdf plugin-list | grep deno >&/dev/null; then
    exe asdf plugin-add terraform
  fi
  exe asdf install terraform latest
}
