#!/usr/bin/env bash

# is_installed() {
#   npm ls -g @mizchi/readability >/dev/null 2>&1
# }
install_common() {
  # go_install github.com/mackee/go-readability/cmd/readability@latest
  npm_install @mizchi/readability
}
