#!/bin/bash

install_common() {
  def_install openssh
}

setting_common() {
  # exchange.key setting
  # shellcheck disable=SC2154
  make_lnk_with_bkup $app_dir/.exchange.key ~/.exchange.key

  # .ssh directory setting
  # link .ssh not work
  # link_to_dot
  if ! is_msys; then
    change_to_right_permission
  fi
}

change_to_right_permission() {
  local ssh_dir=${HOME}/.ssh
  if [ ! -e ${ssh_dir} ]; then
    # exe mkdir -p ${ssh_dir}
    echo "No .ssh directory exists."
    return 0
  fi
  if ! stat -c "%a %n" ${ssh_dir} | grep 755 >/dev/null 2>&1; then
    exe chmod 755 ${ssh_dir}
  fi

  local files=$(find ${ssh_dir}/ -type f)
  for file in $files; do
    if stat -c "%a %n" ${file} | grep -v 600 >/dev/null 2>&1; then
      exe chmod 600 ${file}
    fi
  done
}

# link_to_dot() {
#   ssh_inner=$app_dir/.ssh
#   ssh_outer=${HOME}/.ssh
#
#   if [ ! -e $ssh_inner ]; then
#     exe mkdir -p $ssh_inner
#     exe chmod 755 $ssh_inner
#   fi
#
#   local inner_count=$(ls $ssh_inner/ | wc -l)
#   local outer_count=$(ls $ssh_outer/ | wc -l)
#   if [ $inner_count -eq 0 ] && [ $outer_count -ne 0 ]; then
#     exe mv $ssh_outer/* $ssh_inner/
#   fi
#   make_lnk_with_bkup $ssh_inner $ssh_outer
# }
