version: '3.7'
services:
  db:
    # image: postgres:9.6.14
    build: ./build
    container_name: postgres
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_PASSWORD=secret
      # - POSTGRES_INITDB_ARGS="--encoding=UTF-8 --locale=C"
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
