#!/usr/bin/env bash

is_installed() {
  if is_win || is_wsl; then
    scoop info dbeaver | grep Version >&/dev/null
    return
  fi
  if is_arch; then
    pacman -Qi dbeaver >&/dev/null
    return
  fi
  if is_mac; then
    has_cask dbeaver-community
    return
  fi
  return 1
}
install_common() { not_supported; }
install_wsl() {
  exe scoop install dbeaver
}
install_arch() {
  install_via_os_default
}
install_msys() {
  install_wsl
}
install_cygwin() { not_supported; }
install_mac() {
  exe brew install --cask dbeaver-community
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
