#!/bin/bash

install_common() {
  if ! has pip; then
    log "No pip installed"
    return
  fi
  exe sudo pip install flake8 hacking flake8-import-order flake8-docstrings pep8-naming flake8-double-quotes yapf isort
}
install_msys()   { not_supported; }
setting_common() {
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/flake8" "$HOME/.config/flake8"
}
setting_msys()   { no_settings; }

