#!/usr/bin/env bash

install_common() {
  # setup for posix system
  if ! has go; then
    echo "No go exist. install it." 1>&2
    return
  fi
  exe go install github.com/jesseduffield/lazydocker@latest
}
# install_arch()   {
#   exe git clone https://aur.archlinux.org/lazydocker.git ~/lazydocker
#   exe cd ~/lazydocker
#   exe makepkg --install
# }
# install_msys()   { not_supported; }
# install_cygwin() { not_supported; }
# install_mac()    { not_supported; }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
