#!/usr/bin/env bash

install_common() {
  go_install github.com/jesseduffield/lazydocker@latest
}
# install_arch()   {
#   exe git clone https://aur.archlinux.org/lazydocker.git ~/lazydocker
#   exe cd ~/lazydocker
#   exe makepkg --install
# }
