#!/bin/bash

install_msys() { ;: }
install_cygwin() { ;: }
install_ubuntu() {
    _install_common
}
install_redhat() {
    _install_common
}
install_mac() {
    _install_common
}

_install_common() {
    mexe git clone https://github.com/junegunn/fzf.git ~/.fzf
    mexe ~/.fzf/install
}

