#!/usr/bin/env bash

install_common() {
  go_install github.com/jedisct1/piknik@latest
}
setting_common() {
  _setup_toml_if_needed
  _cat_tips_for_setup_as_server
}

_setup_toml_if_needed() {
  local _target="$HOME/.pikknik.toml"
  if [[ -e $_target ]]; then
    wlog "$_target already exists, skipping creation."
    return
  fi
  exe piknik -genkeys >"$_target"
  exe chmod 600 "$_target"
}

_cat_tips_for_setup_as_server() {
  local _target="$HOME/.pikknik.toml"
  ilog "===> Server Mode Setup Tips"
  # shellcheck disable=SC2154
  cat <<EOF
  ## Install piknik to/usr/local/bin/piknik
  sudo cp -fpv "$GOBIN/piknik" /usr/local/bin/piknik
  ## Move Generated keys
  sudo mv $_target /root/.piknik.toml
  sudo chown root:root /root/.piknik.toml
  ## Copy piknik.service to /etc/systemd/system
  sudo cp "$app_dir"/piknik.service /etc/systemd/system/
  # Reload systemd manager configuration
  sudo systemctl daemon-reload
  # Enable the service to start on boot
  sudo systemctl enable piknik.service
  # Start the service
  sudo systemctl start piknik.service
EOF
}
