#!/usr/bin/env bash

main() {
  # head -3 |
  # tail -1 |
  # set -x
  find $HOME/.vim/conf.d/*vim -type f |
    grep -v 200_colorscheme.vim |
    grep -v 000_init_plug.vim |
    while read -r line; do
      [[ -z $line ]] && continue
      [[ $line =~ ^#.* ]] && continue
      echo ">>> $line"
      if ! grep 'g:plug.is_installed' $line >&/dev/null; then
        continue
      fi
      local _start=$(grep -n 'g:plug.is_installed' $line | head -1 | cut -d: -f1)
      echo $_start
      local _end=$((_start + 2))
      local _plug=$(grep 'g:plug.is_installed' $line | cut -d\" -f2)
      echo "> changing $line .. $_plug"
      sed -i -e "$_start,$_end s,^,\",g" $line
      sed -i -e "$_start s,^,UsePlugin '$_plug'\n,g" $line
    done
}
main "$@"
