#!/usr/bin/env bash

install_common() {
  dl_unzip https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
  exe sudo ./aws/install
}

install_mac() {
  dl_unzip https://awscli.amazonaws.com/AWSCLIV2.pkg
  exe sudo installer -pkg AWSCLIV2.pkg -target /
}
