#!/usr/bin/env bash

install_common() {
  _arch=$(uname -m)
  dl_unzip https://awscli.amazonaws.com/awscli-exe-linux-"$_arch".zip
  exe sudo ./aws/install
}

install_arch() {
  def_install aws-cli-v2
}

install_mac() {
  cd_work
  dl https://awscli.amazonaws.com/AWSCLIV2.pkg AWSCLIV2.pkg
  exe sudo installer -pkg AWSCLIV2.pkg -target /
}
