#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  # https://wiki.archlinux.jp/index.php/Snap
  cd_work
  exe git clone https://aur.archlinux.org/snapd.git
  exe cd snapd
  exe makepkg -si --noconfirm
  exe sudo systemctl start --now snapd.socket
  exe sudo systemctl enable --now snapd.socket
  exe sudo ln -s /var/lib/snapd/snap /snap
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  if grep /snap/bin ~/.works.zsh >&/dev/null; then
    return
  fi
  # exe "echo 'add_path /snap/bin' >> ~/.works.zsh"
  add_path "/snap/bin"
  rm_dotpath
}
# setting_arch() { not_supported; }
# setting_msys() { not_supported; }
# setting_cygwin() { not_supported; }
# setting_mac() { not_supported; }
# setting_ubuntu() { not_supported; }
# setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
