#!/usr/bin/env bash

install_common() {
  # github https://github.com/pdfcpu/pdfcpu
  # exe cd pdfcpu/cmd/pdfcpu
  go_install github.com/pdfcpu/pdfcpu/cmd/...@latest
  # exe cd $GOPATH/src/github.com/pdfcpu/pdfcpu/cmd/pdfcpu
  # go_install
  # exe pdfcpu version
}
