#!/usr/bin/env bash

readonly win_tools=$HOME/win/tools
readonly wsl_terminal=$win_tools/wsl-terminal

is_installed() { [[ -e $wsl_terminal ]]; }

get_latest_url() {
  local part="$(curl -fSsl https://github.com/mskyaxl/wsl-terminal/releases |
    grep href | grep download | grep zip | head -1 |
    sed -e 's/^.\+href="//g' |
    sed -e 's/".\+//g')"
  echo "https://github.com$part"
}

install_common() { not_supported; }
install_arch() { not_supported; }
install_msys() {
  local url=$(get_latest_url)
  dl_unzip "$url" "$wsl_terminal"
}
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
