#!/usr/bin/env bash

install_common() { not_supported; }
install_arch()   { not_supported; }
install_msys()   { not_supported; }
install_cygwin() { not_supported; }
install_mac()    { not_supported; }
install_ubuntu() {
    # support For ubuntu 16.04
    # sudo add-apt-repository -y ppa:geany-dev/ppa
    # sudo apt-get update
    # sudo apt-get upgrade
    install_via_os_default
}
install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_arch()   { not_supported; }
setting_msys()   { not_supported; }
setting_cygwin() { not_supported; }
setting_mac()    { not_supported; }
setting_ubuntu() {
    local confd=$HOME/.config/geany
    make_lnk_with_bkup "$script_path/geany.conf" "$confd/geany.conf"
    make_lnk_with_bkup "$script_path/keybindings.conf" "$confd/keybindings.conf"

    local conffd=$confd/filedefs
    mexe tar xvfpz "$script_path/oblivion2.tar.gz" -C $conffd
    mexe cp $conffd/filetypes.xml $conffd/filetypes.html
    sed 's/^selection.+$/selection=0x000;0x33B5E5;false;true/g' $conffd/filetypes.common

    log "- Themeを[ここ](http://www.geany.org/Download/Extras)からダウンロード"
    log "- [色設定の為、最新にUPDATE](http://enwarblog.blogspot.jp/2012/08/geany.html)"
    log "- oblivion2.tar.gz"
    log "    - 解凍し、~/.config/geany/filedefs へ配置"
    log "- htmlの色変更"
    log "    - htmlファイルがバグっているので、filetype.htmlは、filetype.xmlからコピーし貼付け"
    log "- 選択時の色を赤から変更"
    log "    - filetypes.commom"
    log "#selection=0x000;0xA52A2A;false;true"
    log "selection=0x000;0x33B5E5;false;true"
}
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#gh
#gh_user_local

