#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  ! os wsl && not_supported
  setting_msys
}
install_msys() {
  exe scoop install windows-terminal
}
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() {
  ! os wsl && not_supported
  setting_msys
}
setting_msys() {
  local dst1="${WINHOME}/AppData/Local/Microsoft/Windows Terminal/settings.json"
  local dst2="${WINHOME}/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json"
  local dst=$dst1
  [[ ! -e $dst ]] && dst=$dst2
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/settings.json" "${dst}"
  exe winln -q $WINHOME/scoop/apps/windows-terminal/current/wt.exe
  exe winln -q $app_dir/sudo_wt.bat
}
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
