#!/usr/bin/env bash

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() {
  # def_install libwebp
  def_install libwebp-utils
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  install_via_os_default
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
