#!/usr/bin/env bash

is_installed() {
  if is_mac; then
    if hascask virtualbox && hascask vagrant; then
      return 0
    fi
  fi
  if has vagrant; then
    return 0
  else
    return 1
  fi
}
hascask() { brew list --cask | grep $1 >&/dev/null; }
caskinstall() {
  local pkg=$1
  if hascask $pkg; then
    return
  fi
  exe brew cask install --cask $pkg
}
install_common() { not_supported; }
install_arch() { not_supported; }
install_msys() {
  exe scoop install vagrant
}
install_cygwin() { not_supported; }
install_mac() {
  caskinstall virtualbox
  caskinstall vagrant
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  # check & upgrade virtualbox guest-tools auto
  # exe vagrant plugin install vagrant-vbguest
  exe vagrant plugin install vagrant-disksize
  log "Add Vagrantfile bellow "
  log "   config.disksize.size = '150GB'"
  exe vagrant plugin install vagrant-winnfsd
  log "Add Vagrantfile bellow "
  log '   config.vm.synced_folder ".", "/var/www/src", type: "nfs"'
}
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
