#!/usr/bin/env bash

is_installed() {
  if is_mac; then
    if hascask virtualbox && hascask vagrant; then
      return 0
    fi
  fi
  return 1
}
hascask() { brew cask list |grep $1 >& /dev/null; }
caskinstall() {
  local pkg=$1
  if hascask $pkg; then
    return
  fi
  mexe brew cask install $pkg
}
install_common() { not_supported; }
install_arch()   { not_supported; }
install_msys()   {
  mexe scoop install vagrant
}
install_cygwin() { not_supported; }
install_mac()    {
  caskinstall virtualbox
  caskinstall vagrant
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  # check & upgrade virtualbox guest-tools auto
  # mexe vagrant plugin install vagrant-vbguest
  mexe vagrant plugin install vagrant-disksize
  log "Add Vagrantfile bellow "
  log "   config.disksize.size = '150GB'"
  mexe vagrant plugin install vagrant-winnfsd
  log "Add Vagrantfile bellow "
  log "   config.vm.synced_folder \".\", \"/var/www/src\", type: \"nfs\""
}
setting_arch()   { not_supported; }
setting_msys()   { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#gh
#gh_user_local
