#!/usr/bin/env bash

readonly chrom_rdp_path=$HOME/.config/chrome-remote-desktop

is_installed() { test -e "$chrom_rdp_path"; }
install_arch() {
  def_install chrome-remote-desktop
}
install_ubuntu() {
  cd_work
  exe wget 'https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb'
  exe sudo apt install chrome-remote-desktop_current_amd64.deb
  exe mkdir "$chrom_rdp_path"
  log "=> Success to install! Access chrome remote descktop https://remotedesktop.google.com/access/"
}

setting_common() {
  tips
}
tips() {
  cat <<'EOF' | inki
- setup
  `crd --setup`
EOF
}
