#!/bin/bash

install_msys() {
    cd_work
    version=2.1.4
    mexe wget https://osdn.jp/projects/nkf/downloads/64158/nkf-${version}.tar.gz
    mexe tar zxvf nkf-${version}.tar.gz
    mexe cd nkf-${version}
    mexe make
    mexe mkdir -p /usr/local/bin
    mexe make install
}

install_arch()   {
    if ! has yaourt; then
        echo "No anyenv exist. install it." 1>&2
        return
    fi
    mexe yaourt -S --noconfirm nkf
}

