#!/usr/bin/env bash

install_common() {
  if ! has go; then
    log "golang not installed."
    return
  fi
  exe go install github.com/x-motemen/ghq@latest
}

cat_add_config() {
  cat <<EOF
[ghq]
; primary is last setting
	root = ~/src
	root = ~/go/src
	root = ~/ghq
EOF
}

setting_common() {
  local _gitconfig=$HOME/.gitconfig
  if grep ghq $_gitconfig >&/dev/null; then
    return
  fi
  cat_add_config |
    if is_dry; then
      log "==> add to $_gitconfig bellow."
      echo
      cat -
    else
      cat - | tee -a $_gitconfig >/dev/null
    fi
}
