#!/usr/bin/env bash

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() {
  exe sudo add-apt-repository ppa:ikuya-fruitsbasket/fcitx5
  exe sudo apt upgrade
  exe sudo apt install fcitx5-mozc
  exe im-config -n fcitx5
}
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
