#!/usr/bin/env bash

is_installed() { has fcitx5; }
install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() {
  def_install fcitx5-im fcitx5-mozc
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() {
  exe sudo add-apt-repository ppa:ikuya-fruitsbasket/fcitx5
  exe sudo apt upgrade
  exe sudo apt install fcitx5-mozc
  exe im-config -n fcitx5
}
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() {
  local target_d=$HOME/.config/autostart
  local target_n=org.fcitx.Fcitx5.desktop
  local target=$target_d/$target_n
  if [[ ! -e $target ]]; then
    exe cp /usr/share/applications/$target_n "$target_d"
  fi

  # [fcitxでCtrl+;を押したらクリップボード履歴が出る問題 - HacoLab](https://hacolab.hatenablog.com/entry/2020/03/01/095656)
  target=$HOME/.config/fcitx/addon/fcitx-clipboard.conf
  if [[ ! -e $target ]]; then
    make_dir_if_needed "$(dirname "$target")"
    cat_fcitx_clipboard_conf |
      cat_tee -a "$target"
  fi
  if "$DOT_PATH"/bin/is_wayland; then
    setting_arch_for_wayland
  else
    setting_arch_for_x
  fi
}
setting_arch_for_wayland() {
  target=/etc/environment
  if [[ -e $target ]]; then
    if grep GTK_IM_MODULE=fcitx "$target" >&/dev/null; then
      return
    fi
  fi
  cat_fcitx_env |
    sudo_tee -a "$target"
}
setting_arch_for_x() {
  # [環境変数 - ArchWiki](https://wiki.archlinux.jp/index.php/%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0)
  # > ~/.pam_environment の読み込みは非推奨になり、
  # > この機能は将来のある時点で削除される予定です。
  target=$HOME/.pam_environment
  if [[ -e $target ]]; then
    if grep DEFAULT=fcitx "$target" >&/dev/null; then
      return
    fi
  fi
  cat_pam_environment |
    cat_tee -a "$target"

  # target=$HOME/.xprofile
  # if [[ -e $target ]]; then
  #   if grep GTK_IM_MODULE=fcitx "$target" >&/dev/null; then
  #     return
  #   fi
  # fi
  # cat_fcitx_env |
  #   cat_tee -a "$target"
  # exe fcitx-autostart
}
cat_pam_environment() {
  cat <<'EOF'
GTK_IM_MODULE DEFAULT=fcitx
QT_IM_MODULE  DEFAULT=fcitx
XMODIFIERS    DEFAULT=@im=fcitx
EOF
}
cat_fcitx_env() {
  cat <<'EOF'
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
EOF
}
cat_fcitx_clipboard_conf() {
  cat <<'EOF'
[Addon]
Enabled=False
EOF
}
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
