#!/usr/bin/env bash

install_common() {
  exe 'curl -fsSL https://tailscale.com/install.sh | sh'
}
install_mac() {
  exe brew install --cask tailscale
  # exe sudo brew services start tailscale
}

setting_common() {
  log 'sudo tailscale up --accept-dns=true'
}

setting_mac() {
  # log 'sudo tailscale up --accept-dns=true'
  :
}
