#!/usr/bin/env bash

_go_latest() {
  goenv install -l | grep -v beta | tail -1 | awk '{print $1}'
}
install_common() {
  # setup for posix system
  if ! has goenv; then
    echo "No goenv exist. install it." 1>&2
    return
  fi
  local version=$(_go_latest)
  if [[ -z $version ]]; then
    log "No version exist"
    exit 1
  fi
  mexe goenv install $version
  mexe goenv global $version
  mexe goenv rehash
  mexe go version
}

install_msys() {
  def_install mingw-w64-x86_64-go
}
install_cygwin() {
  not_supported
}

setting_common() {
  local version=$(_go_latest)
  if [[ -z $version ]]; then
    log "No version exist"
    exit 1
  fi
  if grep "/go/$version" ~/.works.zsh >&/dev/null; then
    return
  fi
  # make_dir_if_needed $HOME/go/lib/go
  # mexe "echo 'export GOROOT=\$GOPATH/lib/go' >> ~/.works.zsh"
  # mexe "echo 'export GOBIN=\$GOPATH/bin' >> ~/.works.zsh"
  # mexe "echo 'add_path \$GOBIN' >> ~/.works.zsh"
  # mexe "echo 'export GOPATH=\$HOME/go' >> ~/.works.zsh"
  # mexe "echo 'add_path \$GOPATH/bin' >> ~/.works.zsh"
  local _gobin=$GOPATH/bin
  if [[ ! -e $_gobin ]]; then
    mexe mkdir -p $_gobin
  fi
  mexe "echo 'add_path $GOPATH/bin' >> ~/.works.zsh"
  rm_dotpath
}
