#!/usr/bin/env bash

_go_latest() {
  goenv install -l | grep -v beta | tail -1 | awk '{print $1}'
}
install_common() {
  # setup for posix system
  if ! has goenv; then
    echo "No goenv exist. install it." 1>&2
    return
  fi
  local version=$(_go_latest)
  if [[ -z $version ]]; then
    log "No version exist"
    exit 1
  fi
  exe goenv install $version
  exe goenv global $version
  exe goenv rehash
  exe go version
}

install_arch() {
  install_via_os_default
}

install_ubuntu() {
  exe sudo add-apt-repository -y ppa:longsleep/golang-backports
  exe sudo apt update -y
  exe sudo apt install -y golang-go
}

install_msys() {
  def_install mingw-w64-x86_64-go
  # exe scoop install go
}
install_cygwin() {
  not_supported
}

setting_common() {
  local _gobin=$HOME/go/bin
  make_dir_if_needed $_gobin
  if grep "GOPATH" ~/.works.zsh >&/dev/null; then
    return
  fi
  exe "echo 'export GOPATH=\$HOME/go' >> ~/.works.zsh"
  exe "echo 'add_path \$GOPATH/bin' >> ~/.works.zsh"
  rm_dotpath
}
