#!/usr/bin/env bash

# kakehashi: Tree-sitter ベースの汎用 LS。GitHub Releases のバイナリを導入する。
# https://github.com/atusy/kakehashi/releases
install_common() {
  local os arch target
  os=$(uname -s)
  arch=$(uname -m)
  case "$os-$arch" in
    Linux-x86_64) target="x86_64-unknown-linux-gnu" ;;
    Linux-aarch64 | Linux-arm64) target="aarch64-unknown-linux-gnu" ;;
    Darwin-x86_64) target="x86_64-apple-darwin" ;;
    Darwin-arm64 | Darwin-aarch64) target="aarch64-apple-darwin" ;;
    *)
      elog "Unsupported platform: $os-$arch"
      return 1
      ;;
  esac
  dl_gh_release atusy/kakehashi latest "*-$target.tar.gz"
  exe 'tar -xzf *.tar.gz'
  exe 'sudo cp kakehashi /usr/local/bin/'
}
