#!/usr/bin/env bash

install_common() {
  # setup for posix system
  if ! has anyenv; then
    echo "No anyenv exist. install it." 1>&2
    return
  fi
  exe anyenv install goenv
}

install_msys() { not_supported; }
install_cygwin() { not_supported; }

setting_common() {
  exe "echo 'add_path \${GOPATH}/bin' >> ~/.works.zsh"
  # see https://ksoichiro.blogspot.com/2020/01/ghqpeco.html
  exe "echo 'export GOENV_DISABLE_GOPATH=1' >> ~/.works.zsh"
  rm_dotpath
}
setting_arch() { not_supported; }
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
