#!/usr/bin/env bash

install_common() {
    # setup for posix system
    if ! has anyenv; then
        echo "No anyenv exist. install it." 1>&2
        return
    fi
    mexe anyenv install goenv
    mexe "echo 'add_path \${GOPATH}/bin' >> ~/.works.zsh"
    rm_dotpath
}

install_msys()   { not_supported; }
install_cygwin() { not_supported; }

setting_common() { not_supported; }
setting_arch()   { not_supported; }
setting_msys()   { not_supported; }
setting_cygwin() { not_supported; }
setting_mac()    { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }

