#!/usr/bin/env bash

install_common() {
  # local _zshrc="$HOME"/.dot/apps/zsh/.zshrc
  # _setup_bunsh || :
  # exe chmod u+w "$_zshrc"
  if ! has asdf; then
    add_dependency_args asdf
    return
  fi
  if ! asdf plugin-list | grep bun >&/dev/null; then
    exe asdf plugin-add bun
  fi
  exe asdf install bun latest
}

# _setup_bunsh() {
#   # Disabled auto merge zshrc if .zshrc writable in bun.sh/install
#   exe chmod u-w "$_zshrc"
#   if is_dry; then
#     log "==> Install via https://bun.sh/install | bash"
#   else
#     curl -fsSL https://bun.sh/install | bash
#     # Manually add the directory to ~/.zshrc (or similar):
#     #   export BUN_INSTALL="$HOME/.bun"
#     #   export PATH="$BUN_INSTALL/bin:$PATH"
#     # ==> Path already added in 10.init.zsh, 20.dynamic.zsh
#     rm_dotpath
#   fi
# }

# install_wsl() { not_supported; }
# install_arch() {
#   install_via_os_default
# }
# install_msys() { not_supported; }
# install_cygwin() { not_supported; }
# install_mac() { not_supported; }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
