#!/usr/bin/env bash

install_common() {
  install_via_os_default
}
# install_arch()   {}
# install_msys()   {}
install_cygwin() { not_supported; }
# install_mac()    {}
# install_ubuntu() {}
install_redhat() {
  def_install epel-release
  def_install ShellCheck
}
setting_common() { not_supported; }
setting_arch() { not_supported; }
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#gh
#gh_user_local
