#!/usr/bin/env bash

is_installed() {
  if ! is_mac; then
    return 1
  fi
  has utmctl
}

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  def_install --cask utm
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() {
  log "Download Image from https://mac.getutm.app/gallery/archlinux-arm"
}
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
