#!/usr/bin/env bash

# settings_d_msys="${WINHOME}/AppData/Roaming/Code/User"
# settings_d_msys="${WINHOME}/scoop/persist/vscode/data/user-data/User"
settings_d_mac="${HOME}/Library/Application Support/Cursor/User"
settings_d_linux="$HOME/.config/Cursor/User"

# install_arch() {
#   def_install cursor-extracted
#   make_link_to_bin cursor
# }

_fnm=
install_common() {
  if is_mac; then
    def_install --cask cursor
  else
    log "==> Install from https://cursor.com/ja/download. Use Linux AppImage"
    exe open https://cursor.com/ja/download
    exe read -p "Press Enter after download"
    local _bin
    _bin=$(_find_binary)
    if [[ -z $_bin ]]; then
      log "==> No binary found"
      return
    fi
    exe chmod +x "$_bin"
    _fnm=$(basename "$_bin")
    exe mv -v "$_bin" ~/tools/
  fi
  make_link_to_bin cursor
}

_find_binary() {
  find ~/Downloads/ -maxdepth 1 -mindepth 1 -name '?ursor-*.AppImage' -type f |
    fzf -1 -0 || :
}

setting_common() {
  _ln_jsons "$settings_d_linux"
}
setting_mac() {
  _ln_jsons "$settings_d_mac"
}
_ln_jsons() {
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/settings.json" "$1/settings.json"
  make_lnk_with_bkup "$app_dir/keybindings.json" "$1/keybindings.json"
}
