#!/usr/bin/env -S bash -e

find_cursor_bin() {
  local cursor_bin=/opt/cursor/usr/share/cursor/cursor
  if [[ -x $cursor_bin ]]; then
    echo "$cursor_bin"
    return
  fi
  if os mac; then
    echo "/Applications/Cursor.app/Contents/MacOS/Cursor"
    return
  fi
  find "$HOME"/tools/ -name "cursor-*.AppImage" | sort -r | head -1
}

is_process_already_exists() {
  pgrep -f "$*" >/dev/null
}

start_cursor() {
  "$cursor_bin" "$@" >>/tmp/cursor.log 2>&1 &
}

closest_dirname() {
  if [[ -d $1 ]]; then
    echo "$1"
    return
  fi
  dirname "$1"
}

get_git_root_or_current_dir() {
  if [[ $# -ne 0 ]]; then
    cd "$(closest_dirname "$1")"
  fi
  git rev-parse --show-toplevel 2>/dev/null || pwd
}

main() {
  cursor_bin=$(find_cursor_bin)
  if [[ $# -eq 0 ]]; then
    start_cursor "$(get_git_root_or_current_dir)"
    return
  fi

  if ! is_process_already_exists "$cursor_bin"; then
    start_cursor "$(get_git_root_or_current_dir "$1")"
    sleep 0.5
  fi
  start_cursor "$@"
}
main "$@"
