#!/usr/bin/env bash

script_dir=$(cd "$(dirname "${BASH_SOURCE:-$0}")" && pwd) && readonly script_dir

imp() {
  echo "Not supported yet"
  # cat <"$script_dir"/extensions |
  #   while read -r line; do
  #     "$_bin" --install-extension "$line"
  #   done
}

exp() {
  list_extensions |
    tee "$script_dir"/extensions
}

list_extensions() {
  # "$_bin" --list-extensions
  find ~/.cursor/extensions/ -maxdepth 1 -mindepth 1 -type d |
    sed -e 's,.*/,,g' -e 's,\-[0-9].*,,g' |
    sort
}

main() {
  _bin="$(command -p -v cursor)"
  if [[ $# -eq 0 ]]; then
    exp
    return
  fi
  imp
}
main "$@"
