#!/bin/bash

install_common() {
  if ! has go; then
    log "No golang installed"
    exit 2
  fi
  # ソースコード取得
  cd_work
  exe git clone https://github.com/spf13/hugo
  exe cd hugo
  exe go install --tags extended
}

