#!/usr/bin/env bash

is_installed() { sudo systemctl status nscd.service >&/dev/null; }

install_common() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() {
  exe sudo apt-get install ldap-auth-client nscd

  # For recreate.
  #       dpkg-reconfigure ldap-auth-config
  # Not tested bellow.
  #     cat <<EOF>/usr/share/pam-configs/mkhomedir
  # Name: Create home directory on login
  # Default: yes
  # Priority: 900
  # Session-Type: Additional
  # Session:
  #         required    pam_mkhomedir.so umask=0022 skel=/etc/skel
  # EOF
  exe sudo pam-auth-update
  exe sudo auth-client-config -t nss -p lac_ldap
  exe sudo systemctl restart nscd.service
}
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
