#!/bin/bash

gen_profiled() {
  (cat << EOF
#!/bin/bash

screenfetch
EOF
) |
  if is_dry; then
    echo "---------------------------------------- Gen /etc/profile.d/screenfetch.sh"
    cat - 1>&2
    echo "----------------------------------------"
  else
    cat - |sudo tee /etc/profile.d/screenfetch.sh >&/dev/null
  fi
  mexe sudo chmod 775 /etc/profile.d/screenfetch.sh
}

install_common() {
  install_via_os_default
}
setting_common() {
  gen_profiled
}

