#!/bin/bash

install_ubuntu() {
    mexe sudo apt-get install -y autoconf libtool pkg-config libevent-dev autotools-dev automake build-essential libncurses5-dev
    _install_common
}
install_redhat() {
    mexe sudo yum install -y libevent libeventdevel automake ncursesdevel
    _install_common
}

_install_common() {
    local target_dir=/usr/local/src/tmux
    if [[ ! -e $target_dir ]]; then
        mexe sudo git clone https://github.com/tmux/tmux.git $target_dir
    fi
    if [[ -e $target_dir ]]; then
        cd $target_dir
        local tag=$(git tag --list | tail -1)
        if [[ ! -z $tag ]]; then
            mexe sudo git checkout $tag
        fi
    fi
    mexe sudo ./autogen.sh
    mexe sudo ./configure --prefix=/usr/local
    mexe sudo make
    mexe sudo make install
}

setting_common() {
    make_link_dot2home $app_dir
}

