#!/bin/bash

install_ubuntu() {
    dvexec sudo apt-get install -y autoconf libtool pkg-config libevent-dev autotools-dev automake build-essential libncurses5-dev 
    _install_common
}
install_redhat() {
    dvexec sudo yum install -y libevent libeventdevel automake ncursesdevel
    _install_common
}

_install_common() {
    local target_dir=/usr/local/src/tmux
    if [[ ! -e $target_dir ]]; then
        dvexec sudo git clone https://github.com/tmux/tmux.git $target_dir
    fi
    if [[ -e $target_dir ]]; then
        cd $target_dir
        local tag=$(git tag --list | tail -1)
        if [[ ! -z $tag ]]; then
            dvexec sudo git checkout $tag
        fi
    fi
    dvexec sudo ./autogen.sh
    dvexec sudo ./configure --prefix=/usr/local
    dvexec sudo make
    dvexec sudo make install
}

setting_common() {
    make_link_dot2home $app_dir
}

