#!/usr/bin/env bash

ANDROID_SDK_HOME=$HOME/Android/Sdk
ANDROID_PLATFOME_TOOLS=$ANDROID_SDK_HOME/platform-tools

is_installed() {
  if has sdkmanager && test -e $ANDROID_PLATFOME_TOOLS; then
    return 0
  fi
  return 1
}
install_common() {
  exe sdkmanager --install platform-tools
}
# install_wsl() { not_supported; }
# install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() {
  local target
  target=$HOME/.works.zsh
  if grep $ANDROID_PLATFOME_TOOLS $target >&/dev/null; then
    return
  fi
  cat <<EOF | cat_tee -a $target
add_path $ANDROID_PLATFOME_TOOLS
EOF
  rm_dotpath
}
# setting_wsl() { no_settings; }
# setting_arch() { no_settings; }
# setting_msys() { no_settings; }
# setting_cygwin() { no_settings; }
# setting_mac() { no_settings; }
# setting_ubuntu() { no_settings; }
# setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
