#!/usr/bin/env bash

# current_dir=$(pwd)
# script_dir=$(cd "$(dirname $0)"; pwd)
has() { command -v ${1} >&/dev/null; }

install_ubuntu() {
  # mexe sudo apt-get update
  # def_install linux-headers-generic build-essential
  cd_work
  git clone https://github.com/abperiasamy/rtl8812AU_8821AU_linux.git
  cd rtl8812AU_8821AU_linux
  git co -b hoge 72594b5
  mexe make
  mexe sudo make install
  mexe sudo modprobe rtl8812au
  mexe lsmod | grep rtl8812au
}
install_arch() {
  mexe sudo pacman -S linux-headers
  mexe yay -S rtl8821au-dkms-git
  ## If you remove driver
  # sudo dkms remove rtl8821au/5.1.5.r74.g30fb964 && yay -R rtl8821au-dkms-git

  ## Enale netctl wireless setting
  # sudo cp /etc/netctl/examples/wireless-wpa-static /etc/netctl/wireless
  # sudo vim /etc/netctl/wireless
  # sudo netctl start wireless
}
main() {
  source $DOTPATH/bin/lib/funcs
  tool_env
  if is_arch; then
    install_arch
  elif is_ubuntu; then
    install_ubuntu
  else
    echo "Not supported"
  fi
}

main "$@"
