#!/bin/bash

install_msys() { call_default=1; }
install_cygwin() { call_default=1; }
install_mac() { call_default=1; }
install_ubuntu() { call_default=1; }
install_redhat() { call_default=1; }

setting_msys() { call_default=1; }
setting_cygwin() { call_default=1; }
setting_mac() { call_default=1; }
setting_ubuntu() { call_default=1; }
setting_redhat() { call_default=1; }

# デフォルトのインストールメソッド定義
install() {
    dlog " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    dlog "   Default install called. execute default install command."
    dlog " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    dvexec $def_instcmd
}

# デフォルトの設定メソッド定義
setconfig() {
    dlog " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    dlog "   Default setconfig called. do nothing."
    dlog " >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
}
