#!/usr/bin/env bash

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  def_install --cask iterm2
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_wsl() { not_supported; }
setting_arch() { not_supported; }
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() {
  cat <<'EOF'
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  Do below
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+ 1. General Settings
+   - General - Selection - Check 'Applications in terminal may access clipboard'
+ 1. Appearance Settings
+   - General - Theme - Minimal
+ 1. Profile Settings
+   - Colors - Solorized + Change Background color
+   - Text - font - Osaka - Osaka-Mono 20
+   - Terminal - Notification - Check 'the SilenceBell'
+   - Terminal - Unlimited scroll
+   - Window - Style - Maximized
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
EOF
}
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
