#!/usr/bin/env bash

install_common() {
  npm_install @openai/codex
}

setting_common() {
  log "==> codex"
  log "===> /init"
  make_dir_if_needed "$HOME/.codex"
  make_lnk_with_bkup "$HOME/.mo/codex/AGENTS.md" "$HOME/.codex/AGENTS.md"
  make_lnk_with_bkup "$HOME/.mo/codex/config.toml" "$HOME/.codex/config.toml"
}
