#!/usr/bin/env bash

# install_common() { not_supported; }
# install_common() {
#   if ! has go; then
#     log "golang not installed."
#     return
#   fi
#   # Not work
#   exe go install github.com/cli/cli/cmd/gh@latest
# }
install_arch_by_snap() {
  if ! has snap; then
    log "No snap command exist. install snap first." 1>&2
    return
  fi
  exe sudo snap install gh --edge
}
install_arch() {
  def_install github-cli
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  install_via_os_default
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  if grep 'gh completion -s zsh' ~/.works.zsh >&/dev/null; then
    return
  fi
  exe "echo 'eval \"\$(gh completion -s zsh)\"' >> ~/.works.zsh"
}
# setting_arch() { not_supported; }
# setting_msys() { not_supported; }
# setting_cygwin() { not_supported; }
# setting_mac() { not_supported; }
# setting_ubuntu() { not_supported; }
# setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
