#!/bin/bash

is_installed() { [[ -e /Applications/Karabiner-Elements.app ]]; }
install_common() { not_supported; }
install_arch()   { not_supported; }
install_msys()   { not_supported; }
install_cygwin() { not_supported; }
install_mac()    {
  :
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_arch()   { not_supported; }
setting_msys()   { not_supported; }
setting_cygwin() { not_supported; }
setting_mac()    {
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/.config/karabiner" "$HOME/.config/karabiner"
}
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }

