#!/bin/bash

is_installed() { [[ -e /Applications/Karabiner-Elements.app ]]; }
install_common() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  def_install --cask karabiner-elements
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() {
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/.config/karabiner" "$HOME/.config/karabiner"
}
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
