#!/usr/bin/env bash

# Jedi is a static analysis tool for Python that is typically used in IDEs/editors plugins.
# shellcheck disable=SC2154
is_installed() { has pip && pip list | grep "$app" >&/dev/null; }
install_common() {
  if ! has pip; then
    log "pip not installed."
    return
  fi
  exe pip install jedi
}
