#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  def_install neovim
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  local src=$HOME/.vimrc
  local dst=${HOME}/.config/nvim/init.vim
  local dstd=$(dirname $dst)
  if [[ ! -e $dstd ]]; then
    mexe mkdir -p $dstd
  fi
  make_lnk_with_bkup "$src" "$dst"
}
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#gh
#gh_user_local
