#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  def_install neovim
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  def_install neovim
}
install_ubuntu() {
  exe sudo apt-get install -y software-properties-common
  exe sudo add-apt-repository -y ppa:neovim-ppa/stable
  exe sudo apt-get -y update
  exe sudo apt-get -y install neovim
}
install_redhat() { not_supported; }
setting_common() {
  local src=$HOME/.vimrc
  local dst=${HOME}/.config/nvim/init.vim
  local dstd
  dstd=$(dirname "$dst")
  if [[ ! -e $dstd ]]; then
    exe mkdir -p "$dstd"
  fi
  make_lnk_with_bkup "$src" "$dst"
}
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
#setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
