#!/usr/bin/env bash

is_installed() { [[ -e ~/win/scoop/shims/autohotkey.exe ]]; }
install_common() {
  if ! has scoop; then
    log "scoop not installed."
    return
  fi
  # github https://github.com/karakaram/alt-ime-ahk.git
  exe scoop install autohotkey
}
install_wsl() {
  install_common
}
install_arch() { not_supported; }
install_msys() {
  install_common
}
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  local dst="${WINHOME}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/alt-ime-ahk.ahk"
  [[ -e $dst ]] && return
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/alt-ime-ahk.ahk" "'$dst'"
}
# setting_arch() { no_settings; }
setting_msys() {
  local dst="${WINHOME}/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/alt-ime-ahk.url"
  [[ -e $dst ]] && return
  # shellcheck disable=SC2154
  exe winln "$app_dir/alt-ime-ahk.ahk" "'$dst'"
}
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
