#!/usr/bin/env bash

# shellcheck disable=SC2154
is_installed() { [[ -e "$workdir"/flutter ]]; }
install_common() {
  cd_work
  if [[ ! -e flutter ]]; then
    exe git clone https://github.com/flutter/flutter.git -b stable --depth 1
  fi
  def_install clang cmake ninja
}
# install_arch() { not_supported; }
# install_msys() { not_supported; }
install_cygwin() { not_supported; }
# install_mac() { not_supported; }
# install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  cd_work
  local flutter_bin=$(pwd)/flutter/bin
  if ! grep $flutter_bin ~/.works.zsh >&/dev/null; then
    exe "echo 'add_path $flutter_bin' >> ~/.works.zsh"
    rm_dotpath
  fi
  exe $flutter_bin/flutter precache
  exe $flutter_bin/flutter doctor
}
# setting_arch() { no_settings; }
# setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() {
  setting_common
  if [[ -e /Applications/Xcode.app ]]; then
    exe sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
    exe sudo xcodebuild -runFirstLaunch
    exe sudo xcodebuild -license
  fi
}
# setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
