#!/usr/bin/env bash

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() {
  if os orb; then
    not_supported
    return
  fi
  def_install ttf-nerd-fonts-symbols-mono wezterm
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  exe brew install --cask wezterm
}
install_ubuntu() {
  exe "curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /etc/apt/keyrings/wezterm-fury.gpg"
  echo 'deb [signed-by=/etc/apt/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *' |
    sudo_tee /etc/apt/sources.list.d/wezterm.list
}
install_redhat() { not_supported; }
setting_common() {
  tips_cwd_fork
  if os orb; then
    not_supported
    return
  fi
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/wezterm" "${HOME}/.config/wezterm"
}

tips_cwd_fork() {
  cat <<'EOF' | inki
- Tips for cwd fork
  - Check or add below to .tmux.conf
    ```tmux
    # For wezterm cwd fork: wezterm osc7用に追加
    set -g allow-passthrough on
    ```
  - Check or add below to .works.zsh
    ```zsh
    # For wezterm cwd fork
    __wezterm_osc7() {
      if [[ -n $TMUX ]]; then
        printf '\ePtmux;\e\033]7;file://%s%s\033\\\e\\' "${HOST}" "${PWD}"
        return
      fi
      printf '\e]7;file://%s%s\e\\' "${HOST}" "${PWD}"
    }
    precmd_functions+=(__wezterm_osc7)
    ```
EOF
}
