#!/usr/bin/env bash

current_dir=$(pwd)
script_dir=$(cd $(dirname $0); pwd)

mtp() {
    set -eu
    sudo apt-get install -y libmtp-common mtp-tools libmtp-dev libmtp-runtime libmtp9
    sudo sed -i -e "s/#user_allow_other/user_allow_other/g" /etc/fuse.conf
    sudo sh -c "echo 'ATTR{idVendor}==\"054c\", ATTR{idProduct}==\"0994\", SYMLINK+=\"libmtp-%k\", ENV{ID_MTP_DEVICE}=\"1\", ENV{ID_MEDIA_PLAYER}=\"1\"' > /lib/udev/rules.d/69-mtp.rules"
    sudo service udev restart
}

masstorage() {
    sudo apt-get install -y exfat-fuse exfat-utils
}
main() {
    masstorage
}

main "$@"

