#!/usr/bin/env bash

show_usage() {
  cat <<'EOF'
# Install plugin
tflint --init
# Execute lint
tflint
# Enable lint target for 'modules' directory
tflint --recursive
# Fix lint errors
tflint --recursive --fix
# Specify config
tflint --recursive --config ~/.tflint.hcl
# Enable workflow
# ---
# name: TFLint
#
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#
# jobs:
#   tflint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup TFLint
#         uses: terraform-linters/setup-tflint@v3
#         with:
#           tflint_version: v0.47.0
#       - name: Show version
#         run: tflint --version
#       - name: Run TFLint
#         run: tflint --recursive --config $(pwd)/.tflint.hcl --format compact

# see TFLint: Terraform の Linter を活用しよう - kakakakakku blog https://kakakakakku.hatenablog.com/entry/2023/08/03/133521
EOF
}
install_common() {
  local _cmd='curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash'
  exe "$_cmd"
}
# install_wsl() { not_supported; }
# install_arch() {
#   install_via_os_default
# }
# install_msys() { not_supported; }
# install_cygwin() { not_supported; }
install_mac() {
  install_via_os_default
}
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }

setting_common() {
  make_link_dot2home
  # shellcheck disable=SC2154
  if [[ ! -e $current_dir/.tflint.hcl ]]; then
    # shellcheck disable=SC2154
    exe ln -s "$app_dir"/.tflint.hcl "$current_dir"/.tflint.hcl
  fi
  exe tflint --init
  show_usage
}
# setting_wsl() { no_settings; }
# setting_arch() { no_settings; }
# setting_msys() { no_settings; }
# setting_cygwin() { no_settings; }
# setting_mac() { no_settings; }
# setting_ubuntu() { no_settings; }
# setting_redhat() { no_settings; }
#is_installed
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
