#!/usr/bin/env bash

install_common() {
  go_install github.com/terraform-linters/tflint@latest
}

setting_common() {
  make_link_dot2home
  # # shellcheck disable=SC2154
  # if [[ ! -e $current_dir/.tflint.hcl ]]; then
  #   # shellcheck disable=SC2154
  #   exe ln -s "$app_dir"/.tflint.hcl "$current_dir"/.tflint.hcl
  # fi
  # exe tflint --init
  show_usage
}

show_usage() {
  cat <<'EOF'
# Install plugin
tflint --init
# Execute lint
tflint
# Enable lint target for 'modules' directory
tflint --recursive
# Fix lint errors
tflint --recursive --fix
# Specify config
tflint --recursive --config ~/.tflint.hcl
# Enable workflow
# ---
# name: TFLint
#
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#
# jobs:
#   tflint:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Setup TFLint
#         uses: terraform-linters/setup-tflint@v3
#         with:
#           tflint_version: v0.47.0
#       - name: Show version
#         run: tflint --version
#       - name: Run TFLint
#         run: tflint --recursive --config $(pwd)/.tflint.hcl --format compact

# see TFLint: Terraform の Linter を活用しよう - kakakakakku blog https://kakakakakku.hatenablog.com/entry/2023/08/03/133521
EOF
}
