#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  # shellcheck disable=SC2016
  exe '/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
  exe "/usr/local/bin/brew update"
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() {
  if echo ":$PATH:" | grep ":/usr/local/bin:" >&/dev/null; then
    return
  fi
  echo '>> you need to add /usr/local/bin to PATH variable'
  # shellcheck disable=SC2016
  exe 'export PATH=/usr/local/bin:$PATH'
}
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
