#!/usr/bin/env bash

install_common() { not_supported; }
install_arch()   { not_supported; }
install_msys()   { not_supported; }
install_cygwin() { not_supported; }
install_mac()    {
  # maybe already installed
  install_via_os_default
}
install_ubuntu() {
  github_user_local "https://github.com/libarchive/libarchive.git"
  exe sudo build/autogen.sh
  exe sudo ./configure
  exe sudo make
  exe sudo make install
}
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch()   { no_settings; }
setting_msys()   { no_settings; }
setting_cygwin() { no_settings; }
setting_mac()    { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
