#!/usr/bin/env bash

# https://qiita.com/tomi_sheep/items/ddd9c7b0f0f7c774a222
# https://qiita.com/okash1n/items/8929a67a3cd7223fb90c

do_in_host() {
    # 1. Install virtual box. http://www.oracle.com/technetwork/server-storage/virtualbox/downloads/index.html?ssSourceSiteId=otnjp

    # 2. Download arch image iso. http://ftp.tsukuba.wide.ad.jp/Linux/archlinux/iso/latest/

    # 3. Create virtual box new vm.
        # - Enable EFI
        # - Set Storage and mont arch iso
        # - boot.

    # 4. boot arch in virtualbox
    :
}

do_in_guest() {
    loadkeys jp106
    timedatectl set-ntp true

    # 1. setup partition
    # gdisk /dev/sda
    # o n 1 Enter +512M EF00 n 2 Enter Enter 8300 w
    # mkfs.vfat -F32 /dev/sda1
    # mkfs.ext4 /dev/sda2

    # 2. mount partition
    # mount /dev/sda2 /mnt
    # mkdir -p /mnt/boot
    # mount /dev/sda1 /mnt/boot

    # 3. install packages setting
    vi /etc/pacman.d/mirrorlist
    # move the record to top `## Score: 2.0, Japan`

    pacman -Syy
    pacstrap /mnt base base-devel

    genfstab -U /mnt >> /mnt/etc/fstab
    arch-chroot /mnt /bin/bash


    sed -i -e "/en_US.UTF-8/s/^# //g" /etc/locale.gen
    sed -i -e "/ja_JP.UTF-8/s/^# //g" /etc/locale.gen
    locale.gen
    echo LANG=en_US.UTF-8 > /etc/locale.conf
    export LANG=en_US.UTF-8

    cat <<EOF>>/etc/vconsole.conf
KEYMAP=jp106
FONT=lat9w-16
EOF
    rm /etc/localtime
    ln -s /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
    hwclock --systohc --utc

    local _hostname=vagrant
    echo $_hostname > /etc/hostname
    cat <<EOF>>/etc/hosts
127.0.0.1 localhost.localdomain localhost $_hostname
::1   localhost.localdomain localhost $_hostname
EOF
    systemctl enable dhcpcd
    passwd

    pacman -S grub dosfstools efibootmgr
    grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=arch_grub --recheck
    grub-mkconfig -o /boot/grub/grub.cfg
    mkdir /boot/EFI/boot
    cp /boot/EFI/arch_grub/grubx64.efi  /boot/EFI/boot/bootx64.efi

    exit
    umount -R /mnt
    shutdown -h now

    local _user=vagrant
    useradd -m -G wheel -s /bin/bash $_user
    passwd $_user
    visudo
    # uncomment %wheel ALL=(ALL) NOPASSWD: ALL

    cat <<'EOF'>>/etc/pacman.conf
[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$arch
EOF

    pacman -Syy yaourt

    sudo pacman -S linux-lts linux-lts-headers
    sudo grub-mkconfig -o /boot/grub/grub.cfg
    sudo reboot

    sudo pacman -S virtualbox-guest-utils
    sudo systemctl enable vboxservice
    sudo modprobe -a vboxguest vboxsf vboxvideo
    cat <<EOF |sudo tee /etc/modules-load.d/virtualbox.conf
vboxguest
vboxsf
vboxvideo
EOF
    sudo reboot

    yaourt -S openssh
    sudo systemctl start sshd
    sudo systemctl enable sshd

    # setting port forwarding via gui vbox. guest 22 to host 2222

    yaourt -S wget
    wget --no-check-certificate "https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub" -O ~/.ssh/authorized_keys

    # create box
    vagrant package --base archlinux --output arch.box

    # generate sshconfig
    # vagrant ssh-config --host vag >> ~/.ssh/config

    # [clipboard](http://subtech.g.hatena.ne.jp/secondlife/20100526/1274883708)
    # yaourt -S xorg-server-xvfb
    # Xvfb -screen 0 320x240x8 &
    # DISPLAY=:0 VBoxClient --clipboard &
}

main() {
    do_in_host
    do_in_guest
}
main "$@"
