Vagrant.configure("2") do |config|
  config.vm.box = "tro3373/arch"
  config.vm.box_version = "1.0"
  config.vm.synced_folder ".", "/home/vagrant/works", owner: "vagrant", group: "vagrant"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
#     vb.customize [
#       "modifyvm", :id,
#       "--hwvirtex", "on",
#       "--nestedpaging", "on",
#       "--largepages", "on",
#       "--ioapic", "on",
#       "--pae", "on",
#       "--paravirtprovider", "kvm",
#     ]
  end
end
