#!/usr/bin/env bash

install_common() {
  if ! has asdf; then
    add_dependency_args asdf
    return
  fi
  if ! asdf plugin list | grep deno >&/dev/null; then
    exe asdf plugin-add deno
  fi
  exe asdf install deno latest
  local _ver
  _ver=$(asdf list deno 2>/dev/null | tail -1 | tr -d " ")
  # shellcheck disable=SC2016
  exe "asdf global deno $_ver"
}
# install_wsl() { not_supported; }
# install_arch() {
#   install_via_os_default
# }
# install_msys() { not_supported; }
# install_cygwin() { not_supported; }
# install_mac() {
#   install_via_os_default
# }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
