#!/usr/bin/env bash

install_common() {
  cd_work
  local _v=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
  exe "curl -LO 'https://storage.googleapis.com/kubernetes-release/release/$_v/bin/linux/amd64/kubectl'"
  exe chmod +x ./kubectl
  exe sudo mv ./kubectl /usr/local/bin/kubectl
  exe kubectl version --client
}
# install_arch()   { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() {
  exe 'sudo apt-get update && sudo apt-get install -y apt-transport-https gnupg2 curl'
  exe 'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -'
  exe 'echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list'
  exe sudo apt-get update
  exe sudo apt-get install -y kubectl
}
cat_rh_kube_repo() {
  cat <<EOF
  [kubernetes]
  name=Kubernetes
  baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
  enabled=1
  gpgcheck=1
  repo_gpgcheck=1
  gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
}
install_redhat() {
  cat_rh_kube_repo | sudo_tee /etc/yum.repos.d/kubernetes.repo
  exe yum install -y kubectl
}
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
