#!/usr/bin/env bash

install_common() {
  if ! has go; then
    log "golang not installed."
    return
  fi
  exe go get -v -u github.com/mvdan/sh/cmd/shfmt
}

# setting_common() {
#   # shellcheck disable=SC2154
#   make_link_dot2home $app_dir
# }
#
