#!/usr/bin/env bash

install_common() {
  if ! has go; then
    log "golang not installed."
    return
  fi
  exe go install github.com/mvdan/sh/cmd/shfmt@latest
}

# setting_common() {
#   # shellcheck disable=SC2154
#   make_link_dot2home $app_dir
# }
#
