#!/usr/bin/env bash

# shellcheck disable=SC2154
is_installed() { [[ -e $current_dir/node_modules/.bin/biome ]]; }
install_common() {
  if [[ ! -e $current_dir/package.json ]]; then
    exe "(cd $current_dir && npm init)"
  fi
  exe "(cd $current_dir && npm install -D @biomejs/biome)"
}
setting_common() {
  config_json_name="biome.json"
  if is_force || ! test -e "$current_dir"/$config_json_name; then
    # shellcheck disable=SC2154
    exe cp "$app_dir"/$config_json_name "$current_dir"/$config_json_name
  fi
  log "==> Check the biome configuration"
  log "npx biome check --verbose"
}
