#!/usr/bin/env bash

# shellcheck disable=SC2154
is_installed() { [[ -e $current_dir/node_modules/.bin/biome ]]; }
install_common() {
  if [[ ! -e $current_dir/package.json ]]; then
    exe "(cd $current_dir && npm init)"
  fi
  exe "(cd $current_dir && npm install --dev @biomejs/biome)"
}
setting_common() {
  if [[ ! -e $current_dir/biome.json ]]; then
    # shellcheck disable=SC2154
    exe ln -s "$app_dir"/biome.json "$current_dir"/biome.json
  fi
  log "==> Check the biome configuration"
  log "npx biome check --verbose"
}
