#!/usr/bin/env bash

cat_aur_pac_conf() {
  local endpoint_part="\$arch"
  is_arm && endpoint_part=arm
  cat <<EOF
[archlinuxfr]
SigLevel = Never
Server = http://repo.archlinux.fr/$endpoint_part

EOF
}
install_common() { not_supported; }
install_arch()   {
  if ! cat < /etc/pacman.conf |grep repo.archlinux.fr >& /dev/null; then
    cat_aur_pac_conf |
      if is_dry; then
        log "==> add to /etc/pacman.conf bellow."
        echo
        cat -
      else
        cat - |sudo tee -a /etc/pacman.conf >/dev/null
      fi
      mexe sudo pacman -Syy
  fi
  def_install base-devel
  if ! has package-query; then
    dl_untar https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
    mexe cd package-query
    mexe makepkg -si
  fi
  install_via_os_default
}
install_msys()   { not_supported; }
install_cygwin() { not_supported; }
install_mac()    { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_arch()   { not_supported; }
setting_msys()   { not_supported; }
setting_cygwin() { not_supported; }
setting_mac()    { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
