#!/usr/bin/env bash

current_dir=$(pwd)
script_dir=$(cd $(dirname $0); pwd)
command_name=$(basename $0)
dotbin=${DOTPATH:-~/.dot}/bin

win_url=https://varaneckas.com/jad/jad158g.win.zip
mac_url=https://varaneckas.com/jad/jad158g.mac.intel.zip
# lin_url=https://varaneckas.com/jad/jad158e.linux.intel.zip
lin_url=https://varaneckas.com/jad/jad158e.linux.static.zip

has() {
    which ${1} >/dev/null 2>&1
    return $?
}

get_url() {
    local url=$lin_url
    case "$($dotbin/os)" in
        msys) url=$win_url;;
        mac) url=$mac_url;;
    esac
    echo $url
}

mv_to_bin() {
    if [ -e $1 ]; then
        t=$1
    elif [ -e $2 ]; then
        t=$2
    else
        return
    fi
    mv $t ~/bin
    echo "===> $t Installed in ~/bin/"
}

get_and_set_binary() {
    local url="$*"
    [[ ! -e tmp ]] && mkdir tmp
    pushd tmp >/dev/null 2>&1
    echo "===> Downloading from $url .."
    wget $url && unzip ./*.zip && mv_to_bin jad jad.exe
    popd >/dev/null 2>&1
}

main() {
    has jad && echo "Already installed jad in $(which jad)"
    get_and_set_binary $(get_url)
}
main "$@"

