#!/usr/bin/env bash

version=${1:-}
has() {
    which ${1} >/dev/null 2>&1
    return $?
}
intaractive() {
    while [[ "$input_word" == "" ]]; do
        nodenv install -l | grep -v jxcore | grep -v iojs
        echo
        echo "Input install version. Now version is .. "
        node -v
        read input_word
    done
    version=$input_word
}
main() {
    if ! has anyenv; then
        echo "Installing anyenv ..."
        ./setup.sh
    fi
    if ! has nodenv; then
        echo "Installing nodenv ..."
        anyenv install nodenv
    fi
    if has node; then
        echo "Already nodenv installed." 1>&2
        # echo "Upgrading nodenv ..."
        # ./rbenv_upgrade
    fi

    if [[ -z $version ]]; then
        intaractive
    fi
    nodenv install $version
    nodenv global $version
    ruby -v
}
main $*
