#!/usr/bin/env bash

main() {
  if [[ $# -eq 0 ]]; then
    code --list-extensions > extensions
    return
  fi
  cat < extensions |
    while read -r line; do
     code --install-extension $line
    done
}
main "$@"
