#!/usr/bin/env bash

readonly script_dir=$(
  cd "$(dirname ${BASH_SOURCE:-$0})"
  pwd
)

main() {
  if [[ $# -eq 0 ]]; then
    code --list-extensions >$script_dir/extensions
    return
  fi
  cat <$script_dir/extensions |
    while read -r line; do
      code --install-extension $line
    done
}
main "$@"
