#!/usr/bin/env bash

app_d_mac="/Applications/Robo 3T.app"

is_installed() {
  if is_msys || is_wsl; then
    has_scoop robo3t
  elif is_mac; then
    test -e "$app_d_mac"
  fi
}
install_via_scoop() {
  exe scoop install robo3t
}
install_common() { not_supported; }
install_wsl() {
  install_via_scoop
}
install_arch() { not_supported; }
install_msys() {
  install_via_scoop
}
install_cygwin() { not_supported; }
install_mac() {
  def_install --cask robo-3t
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
