#!/usr/bin/env bash

# shellcheck disable=SC2154
is_installed() { has pip && pip list | grep "vim-vint" >&/dev/null; }
install_common() {
  if ! has pip; then
    log "pip not installed."
    return
  fi
  exe pip install vim-vint
}
