#!/bin/bash

is_installed() {
    if is_win; then
        # TODO check program files?
        return 1
    fi
    if has apm; then
        return 0
    else
        return 1
    fi
}

install_ubuntu() {
    make_work_if_needed
    cd_work
    dl https://atom.io/download/deb atom.deb
    dvexec sudo dpkg -i atom.deb
}

install_redhat() {
    make_work_if_needed
    cd_work
    dl https://atom.io/download/rpm atom.rpm
    dvexec sudo rpm -ivh atom.rpm
}

setting_common() {
    make_lnk_with_bkup "$app_dir/.atom" "$HOME/.atom"
}
setting_msys() {
    make_lnk_with_bkup "$app_dir/.atom" "$WINHOME/.atom"
}

