#!/bin/bash

atom_dir_name=atom
is_installed() {
    if has apm; then
        return 0
    fi
    is_win && [[ -e $WINHOME/tools/$atom_dir_name ]] && return 0
    return 1
}

install_msys() {
    cd_work
    dl "$(get_dl_url_win)" dl.zip
    exe unzip dl.zip -d dl
    exe "mv \"dl/Atom x64\" \"$WINHOME/tools/$atom_dir_name\""
}

install_ubuntu() {
    cd_work
    dl https://atom.io/download/deb atom.deb
    exe sudo dpkg -i atom.deb
}

install_redhat() {
    cd_work
    dl https://atom.io/download/rpm atom.rpm
    exe sudo rpm -ivh atom.rpm
}

get_dl_url_win() {
    curl -fsSL https://github.com/atom/atom/releases/latest \
        | grep "a href" \
        | grep "atom-x64-windows.zip" \
        | awk -F\" '{print "https://github.com" $2}'
}

setting_common() {
    make_lnk_with_bkup "$app_dir/.atom" "$HOME/.atom"
}
setting_msys() {
    make_lnk_with_bkup "$app_dir/.atom" "$WINHOME/.atom"
}

