#!/usr/bin/env bash

install_common() { not_supported; }
_install_common() {
  # shellcheck disable=SC2016
  exe 'export PATH="$HOME/.cargo/bin:$PATH'
  # exe cargo install cargo-binstall
  local _latest_tag=v0.22.0
  # _latest_tag=$(github_latest_release_tag cargo-bins/cargo-binstall)
  exe cargo install cargo-binstall --git https://github.com/cargo-bins/cargo-binstall.git --tag "$_latest_tag"
}
install_wsl() { not_supported; }
install_arch() {
  install_via_os_default
  exe rustup default stable
  _install_common
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() {
  def_install rustup-init
  exe rustup-init
  _install_common
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_wsl() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
