#!/bin/bash

install_mac() {
    dvexec brew install global --with-exuberant-ctags --with-pygments
}

install_ubuntu() {
    dvexec "$instcmd python-pip exuberant-ctags ncurses-dev"
    dvexec sudo pip install Pygments
    download_global_src_and_build
    dvexec cp -f /usr/local/share/gtags/gtags.conf ~/.globalrc
    dvexec "sed -ri -e 's/^(\t:tc=native:)/\1tc=pygments:/g' ~/.globalrc"
}

get_global_src_url() {
    local dlpage="https://www.gnu.org/software/global/download.html"
    local url="`curl -s $dlpage | grep -E "global-.+\.tar\.gz" | awk -F"'" '{print $2}'`"
    echo $url
}

download_global_src_and_build() {
    make_work_if_needed
    # http://qiita.com/yoshizow/items/9cc0236ac0249e0638ff
    # ソースコード取得
    cd_work
    if [[ ! -e "$workdir/global.tar.gz" ]]; then
        local dlurl=$(get_global_src_url)
        dvexec curl -sS -o global.tar.gz $dlurl
    fi
    if [[ ! -e "$workdir/global" ]]; then
        dvexec mkdir -p $workdir/global
        dvexec tar xvfpz $workdir/global.tar.gz -C $workdir/global
    fi
    dvexec cd $workdir/global/global*
    dvexec ./configure --prefix=/usr/local
    dvexec make
    dvexec sudo make install
}

