#!/bin/bash

install_mac() {
  exe brew install global --with-exuberant-ctags --with-pygments
}

install_ubuntu() {
  # shellcheck disable=SC2154
  exe "$def_install_cmd python-pip exuberant-ctags ncurses-dev"
  exe sudo pip install Pygments
  download_global_src_and_build
  exe cp -f /usr/local/share/gtags/gtags.conf ~/.globalrc
  exe "sed -ri -e 's/^(\t:tc=native:)/\1tc=pygments:/g' ~/.globalrc"
}

get_global_src_url() {
  local dlpage="https://www.gnu.org/software/global/download.html"
  local url="$(curl -s $dlpage | grep -E "global-.+\.tar\.gz" | awk -F"'" '{print $2}')"
  echo $url
}

download_global_src_and_build() {
  # http://qiita.com/yoshizow/items/9cc0236ac0249e0638ff
  # ソースコード取得
  cd_work
  # shellcheck disable=SC2154
  if [[ ! -e "$workdir/global.tar.gz" ]]; then
    local dlurl=$(get_global_src_url)
    exe curl -sS -o global.tar.gz $dlurl
  fi
  if [[ ! -e "$workdir/global" ]]; then
    exe mkdir -p $workdir/global
    exe tar xvfpz $workdir/global.tar.gz -C $workdir/global
  fi
  exe cd $workdir/global/global*
  exe ./configure --prefix=/usr/local
  exe make
  exe sudo make install
}

