#!/usr/bin/env bash

scoop_idea=IntelliJ-IDEA
def_cmd="$HOME/.local/share/JetBrains/Toolbox/scripts/idea"
mac_cmd="/Applications/IntelliJ IDEA CE.app/Contents/MacOS/idea"

is_installed() {
  if is_mac; then
    test -e "$mac_cmd"
  else
    test -e "$def_cmd"
  fi
}

install_common() { not_supported; }
install_wsl() {
  install_arch
}
install_arch() {
  # def_install intellij-idea-community-edition
  if ! has jetbrains-toolbox; then
    add_dependency_args jetbrains-toolbox
    return
  fi
  log "==> Install via jetbrains-toolbox"
  exe jetbrains-toolbox
}

create_bin_cmd() {
  # shellcheck disable=SC2154
  local _dst="$HOME/bin/$app"
  cat_bin_cmd |
    cat_tee "$_dst"
  exe chmod +x "$_dst"
}

cat_bin_cmd() {
  local _cmd=$mac_cmd
  if ! is_mac; then
    # _cmd="$(command -v -p "$app")"
    _cmd="$def_cmd"
  fi
  cat <<EOF
#!/usr/bin/env -S bash -e

nohup "$_cmd" "\$@" >&/tmp/$app.log &
EOF
}

install_msys() {
  exe scoop install $scoop_idea
}
install_cygwin() { not_supported; }
install_mac() {
  def_install --cask intellij-idea-ce
}
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  # shellcheck disable=SC2154
  make_lnk_with_bkup "$app_dir/_ideavimrc" "$HOME/_ideavimrc"
  create_bin_cmd
}
setting_wsl() {
  make_lnk_with_bkup "$app_dir/_ideavimrc" "$WINHOME/_ideavimrc"
  setting_common
}
# setting_arch() {
#   setting_common
# }
setting_msys() {
  setting_wsl
}
setting_cygwin() { no_settings; }
# setting_mac() {
#   setting_common
# }
# setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
