snippet aptttt
	RUN apt update && \
			apt install -y curl build-essential gcc make && \
			apt clean && \
			rm -rf /var/lib/apt/lists/*

snippet run_cat_eofff
	RUN <<-'EOF' cat >>/entrypoint
	#!/bin/bash
	main() {
		:
	}
	main "$@"
	EOF
