#!/usr/bin/env bash

install_common() { not_supported; }
install_wsl() { not_supported; }
install_arch() {
  def_install postman-bin
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() {
  create_bin_cmd
}
setting_wsl() { no_settings; }
# setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }

create_bin_cmd() {
  # shellcheck disable=SC2154
  local _dst="$HOME/bin/$app"
  if [[ -e $_dst ]]; then
    return
  fi
  cat_bin_cmd |
    cat_tee "$_dst"
  exe chmod +x "$_dst"
}

cat_bin_cmd() {
  local _cmd
  _cmd="$(which "$app")"
  cat <<EOF
#!/bin/bash

set -e

nohup "$_cmd" "\$@" >&/tmp/$app.log &
EOF
}

#add_dependency_args
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#no_settings
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
#sudo_tee
