version: '3.7'
services:
  db:
    image: mysql:5.6.50
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./data:/var/lib/mysql
      - ./logs:/var/log/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
