#!/usr/bin/env bash

install_common() { not_supported; }
install_arch()   {
  if ! has go; then
      log "No go exist. install it." 1>&2
      return
  fi
  cd_work
  if [[ -e terraformer ]]; then
    exe rm -rf terraformer
  fi
  exe git clone https://github.com/GoogleCloudPlatform/terraformer.git
  exe cd terraformer
  exe GO111MODULE=on go mod vendor
  exe go build -v
}
install_msys()   { not_supported; }
install_cygwin() { not_supported; }
install_mac()    { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch()   { no_settings; }
setting_msys()   { no_settings; }
setting_cygwin() { no_settings; }
setting_mac()    { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local

