#!/bin/bash

install_common() {
    # peco 最新バージョンを取得
    peco_latest_version="`get_pecoltver`"
    log "  ===> Peco latest version=${peco_latest_version}"
    dlurl="https://github.com/peco/peco/releases/download/${peco_latest_version}/peco_linux_amd64.tar.gz"
    log "  ===> Donload from url=${dlurl}"

    cd_work
    mexe wget $dlurl
    if [ -e "$app_dir/tmp/peco_linux_amd64.tar.gz" ]; then
        mexe tar xvfpz peco_linux_amd64.tar.gz
        installto=/usr/local/bin
        sudo="sudo"
        if is_cygwin; then
            sudo=""
        fi
        mexe "$sudo cp peco_linux_amd64/peco $installto"
        log "  ===> peco installed to $installto"
    fi
}

install_msys() { :; }
install_cygwin() { :; }

install_mac() {
    mexe sudo brew tap peco/peco
    mexe sudo brew install peco
}

# peco 最新バージョンを取得
get_pecoltver() {
    version="`curl -sI https://github.com/peco/peco/releases/latest | awk -F'/' '/^Location:/{print $NF}' |sed 's/\r//g'`"
    echo "$version"
}

setting_common() {
    if [ ! -e ${HOME}/.config/peco ]; then
        mexe "mkdir -p \"${HOME}/.config/peco\""
    fi
    make_lnk_with_bkup "${app_dir}/config.json" "${HOME}/.config/peco/config.json"
}

