#!/usr/bin/env bash

is_installed() {
  if is_arch; then
    has_local_package rtl8821au-dkms-git
  elif is_ubuntu; then
    lsmod | grep rtl8812au >&/dev/null
  else
    return 1
  fi
}
install_common() { not_supported; }
install_arch() {
  def_install linux-headers
  def_install rtl8821au-dkms-git
  ## If you remove driver
  # sudo dkms remove rtl8821au/5.1.5.r74.g30fb964 && yay -R rtl8821au-dkms-git

  ## Enale netctl wireless setting
  # sudo cp /etc/netctl/examples/wireless-wpa-static /etc/netctl/wireless
  # sudo vim /etc/netctl/wireless
  # sudo netctl start wireless
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() {
  if false; then
    DRV_NAME=rtl8812AU
    DRV_VERSION=4.3.20
    # DRV_VERSION=5.6.4

    if [[ $1 == "-r" ]]; then
      mexe sudo dkms uninstall -m ${DRV_NAME} -v ${DRV_VERSION}
      mexe sudo dkms status
      return
    fi

    if ! has dkms; then
      def_install dkms
    fi
    local srcd=/usr/src/${DRV_NAME}-${DRV_VERSION}

    if [[ ! -e $srcd ]]; then
      mexe sudo git clone https://github.com/diederikdehaas/rtl8812AU $srcd
    fi

    mexe cd /usr/src/${DRV_NAME}-${DRV_VERSION}
    mexe sudo git checkout -b driver-${DRV_VERSION} origin/driver-${DRV_VERSION}
    mexe sudo dkms add -m ${DRV_NAME} -v ${DRV_VERSION}
    mexe sudo dkms build -m ${DRV_NAME} -v ${DRV_VERSION}
    mexe sudo dkms install -m ${DRV_NAME} -v ${DRV_VERSION}
    mexe sudo dkms status
  fi

  # mexe sudo apt-get update
  # def_install linux-headers-generic build-essential
  cd_work
  mexe git clone https://github.com/abperiasamy/rtl8812AU_8821AU_linux.git
  mexe cd rtl8812AU_8821AU_linux
  mexe git checkout -b tmp 72594b5
  mexe make
  mexe sudo make install
  mexe sudo modprobe rtl8812au
  mexe lsmod | grep rtl8812au
}
install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_arch() { not_supported; }
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#gh
#gh_user_local
