#!/usr/bin/env bash

install_common() { not_supported; }
install_arch() {
  exe gpg --recv-keys --keyserver hkp://pgp.mit.edu 1D1F0DC78F173680
  def_install powerpill # Use powerpill instead of pacman. Bye pacman...
  ### =================powerpill SigLevel書き換え===================
  if backup /etc/pacman.conf; then
    exe sudo sed -i -e 's/Required DatabaseOptional/PackageRequired/' /etc/pacman.conf
  fi
  # パッケージ更新
  exe sudo powerpill -Syu --noconfirm
}
install_msys() { not_supported; }
install_cygwin() { not_supported; }
install_mac() { not_supported; }
install_ubuntu() { not_supported; }
install_redhat() { not_supported; }
setting_common() { no_settings; }
setting_arch() { no_settings; }
setting_msys() { no_settings; }
setting_cygwin() { no_settings; }
setting_mac() { no_settings; }
setting_ubuntu() { no_settings; }
setting_redhat() { no_settings; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
