#!/bin/bash

is_installed() { has certbot-auto; }
install_common() {
  src_dir=/opt/letsencrypt
  if [[ ! -d $src_dir ]]; then
    exe sudo git clone https://github.com/letsencrypt/letsencrypt $src_dir
    exe cd $src_dir
  else
    exe cd $src_dir
    exe sudo git pull
  fi
  $HOME/.dot/bin/certbot-auto_
}
# install_arch() { not_supported; }
install_msys() { not_supported; }
install_cygwin() { not_supported; }
# install_mac() { not_supported; }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() { not_supported; }
setting_arch() { not_supported; }
setting_msys() { not_supported; }
setting_cygwin() { not_supported; }
setting_mac() { not_supported; }
setting_ubuntu() { not_supported; }
setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
