#!/usr/bin/env bash

current_dir=$(pwd)
script_dir=$(cd $(dirname $0); pwd)

get_latest_url() {
    local part="$(curl -fSsl https://github.com/goreliu/wsl-terminal/releases \
        | grep href |grep download |grep zip |head -1 \
        | sed -e 's/^.\+href="//g' \
        | sed -e 's/".\+//g')"
    echo "https://github.com$part"
}

main() {
    set -eu
    local wsl_terminal=wsl-terminal
    local win_tools=~/win/tools
    if [[ -e $win_tools/$wsl_terminal ]]; then
        echo "Already setuped to $win_tools." 1>&2
        exit 1
    fi
    local url=$(get_latest_url)
    local work_dir=$script_dir/tmp
    [[ ! -e $work_dir ]] && mkdir -p $work_dir
    cd $work_dir
    if [ ! -e wsl*.zip ]; then
        echo "==> Downloading $url .."
        curl -sSLO $url \
            && unzip wsl*.zip \
            && mv $work_dir/$wsl_terminal $win_tools
    fi
}

main "$@"

