#!/bin/bash

install_ubuntu() {
    # build tool のインストール
    mexe "$instcmd build-essential"
    # https://gist.github.com/raimon49/9d45d480a607fb463ffe
    # 日本語用
    mexe "$instcmd libncursesw5-dev"

    # ソースコード取得
    cd_work
    if [ ! -e "$script_dir/tmp/tig" ]; then
        mexe git clone https://github.com/jonas/tig.git
    fi
    mexe "cd tig"
    mexe git checkout tig-2.1.1

    # ビルド, インストール
    mexe sudo LDLIBS=-lncursesw CFLAGS=-I/usr/include/ncursesw make install prefix=/usr/local
    mexe /usr/local/bin/tig -v
}

install_redhat() {
    #targetrpm="rpmforge-release-0.5.2-2.el6.rf.x86_64"
    #result=`rpm -qa |grep $targetrpm`
    #if [ "$result" = "" ]; then
    #    cmd="sudo rpm -ivh http://pkgs.repoforge.org/rpmforge-release/${targetrpm}.rpm"
    #    mexe "$cmd"
    #fi
    #install_via_os_default
    # ソースコード取得
    cd_work
    if [ ! -e "$workdir/tig" ]; then
        mexe git clone https://github.com/jonas/tig.git
    fi
    mexe "cd tig"
    # mexe git checkout tig-2.1.1

    # ビルド, インストール
    mexe ./autogen.sh
    mexe ./configure prefix=/usr/local
    mexe sudo make
    mexe sudo sudo make install
    mexe /usr/local/bin/tig -v
}

setting_common() {
    make_link_dot2home $app_dir
}
