#!/usr/bin/env bash

install_common() {
  exe cd $HOME/bin
  exe curl -O https://raw.githubusercontent.com/rockymadden/slack-cli/master/src/slack
  exe chmod +x slack
}
# install_arch()   { not_supported; }
# install_msys()   { not_supported; }
# install_cygwin() { not_supported; }
# install_mac()    { not_supported; }
# install_ubuntu() { not_supported; }
# install_redhat() { not_supported; }
setting_common() {
  exe "echo 'export SLACK_CLI_TOKEN=token' >> $HOME/.works.zsh"
}
# setting_arch()   { not_supported; }
# setting_msys()   { not_supported; }
# setting_cygwin() { not_supported; }
# setting_mac()    { not_supported; }
# setting_ubuntu() { not_supported; }
# setting_redhat() { not_supported; }
#is_installed
#install_via_os_default
#def_install
#is_debug
#is_dry
#log
#dlog
#not_supported
#make_link_dot2home
#make_lnk_with_bkup
#cd_work
#make_work_if_needed
#dl
#dl_unzip
#dl_untar
#github
#github_user_local
