#!/bin/bash

#if [ -x /usr/bin/Xvfb ] && [ -x /usr/bin/VBoxClient ] && [ ! -f /tmp/.X0-lock ]; then
#  Xvfb -screen 0 320x240x8 > /dev/null 2>&1 &
#  sleep 0.5
#  DISPLAY=:0 VBoxClient --clipboard
#fi
main() {
    Xvfb -screen 0 320x240x8 &
    DISPLAY=:0 VBoxClient --clipboard &
}
main
