Vagrant.configure("2") do |config|
  config.vm.box = "tro3373/arch"
  config.vm.box_version = "1.0"
  config.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
#     vb.customize [
#       "modifyvm", :id,
#       "--hwvirtex", "on",
#       "--nestedpaging", "on",
#       "--largepages", "on",
#       "--ioapic", "on",
#       "--pae", "on",
#       "--paravirtprovider", "kvm",
#     ]
  end
end
