#!/bin/bash

sublime_dir_name=sublime-text-3
is_installed() {
    if has $app; then
        return 0
    fi
    is_win && [[ -e $WINHOME/tools/$sublime_dir_name ]] && return 0
    return 1
}
install_msys() {
    dl_unzip "$(get_dl_url_win)" "$WINHOME/tools/$sublime_dir_name"
}
install_mac() {
    dl_unzip "$(get_dl_url_mac)"
}
install_ubuntu() {
    # sudo add-apt-repository --remove ppa:webupd8team/sublime-text-3
    # sudo add-apt-repository -y ppa:webupd8team/sublime-text-3
    # sudo apt-get update
    # sudo apt-get install -y sublime-text-installer ibus-mozc emacs-mozc
    exe 'wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -'
    exe sudo apt-get install apt-transport-https
    exe 'echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list'
    exe sudo apt-get update
    exe sudo apt-get install -y sublime-text
}
setting_redhat() {
    exe sudo rpm -v --import https://download.sublimetext.com/sublimehq-rpm-pub.gpg
    exe sudo yum-config-manager --add-repo https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
    exe sudo yum install -y sublime-text
}

setting_common() {
    make_lnk_with_bkup "$app_dir/User" "$HOME/.config/sublime-text-3/Packages/User"
}

setting_msys() {
    WINHOME=${WINHOME:-~/win}
    # make_lnk_with_bkup "$app_dir/User" "$WINHOME/AppData/Roaming/Sublime Text 3/Packages/User"
    local tmp="$WINHOME/tools/$sublime_dir_name/Data/Packages"
    [[ ! -e $tmp ]] && mkdir -p $tmp
    make_lnk_with_bkup "$app_dir/User" "$WINHOME/tools/$sublime_dir_name/Data/Packages/User"
}

setting_mac() {
    make_lnk_with_bkup "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" "/usr/local/bin/subl"
    make_lnk_with_bkup "$app_dir/User" "$HOME/Library/Application Support/Sublime Text 3/Packages/User"
}

get_dl_url_mac() {
    curl -fsSL http://www.sublimetext.com/3 |
        grep "a href" |
        grep download.sublimetext.com |
        grep "OS X" |
        cut -d"\"" -f4
}

get_dl_url_win() {
    curl -fsSL http://www.sublimetext.com/3 |
        grep "a href" |
        grep download.sublimetext.com |
        grep "Windows 64 bit" |
        cut -d"\"" -f6
}

