#!/usr/bin/env bash

install_common() {
  exe 'curl -fsSL https://claude.ai/install.sh | bash'
  # npm_install @anthropic-ai/claude-code
  # suggest
}

suggest() {
  if [[ -e ~/.npm-global ]]; then
    return
  fi
  log "==> Execute 'setup_npm_global' first and Re-Install."
}

# install_mac() {
#   exe brew install --cask claude
# }

setting_common() {
  log "==> claude"
  log "===> /init"
  for item in CLAUDE.md settings.json commands agents skills; do
    make_lnk_with_bkup "$HOME/.mo/claude/$item" "$HOME/.claude/$item"
  done
  show_usage
}

show_usage() {
  cat <<'EOF'
/plugin marketplace add anthropics/skills
  /plugin install document-skills@anthropic-agent-skills
  /plugin install example-skills@anthropic-agent-skills
# https://x.com/_catwu/status/1993791353051074687?t=pVVyagazUFIcfG33Xb5PHw&s=09
/plugin marketplace add anthropics/claude-code
  /plugin install frontend-design@claude-code-plugins
EOF
}
